### ISSUE TITLE
Server not receiving ‘ping’

### ISSUE THREAD

**Issue by NuzumPat** [jaredwolff/nodejs-websocket-example#2]
![servernotreceivingping-04](https://cloud.githubusercontent.com/assets/21071440/19109995/e231adb0-8ac5-11e6-9b22-65842fdadc92.jpg)
![servernotreceivingping-05](https://cloud.githubusercontent.com/assets/21071440/19109996/e23c7754-8ac5-11e6-8510-09a687d22cf6.jpg)

I closed the last issue, but am still having problems getting this example to work.
The server is not receiving the ping sent from the client when the <Click Me> button is pressed.
The client receives a pong every 20 seconds. This must be the keep alive pong.
I’m using the latest jQuery (3.1.1). 
socket.io 1.4.8
I got the client.io.js from: nodejs-websocket-example-master\node_modules\socket.io\node_modules\socket.io-client
It is 180KB.
I even added dependencies from your package.json in the socket.io folder.
I provided some attachments.
Let me know if there is any more information I can provide.
Thanks,
Pat 
![server not receiving ping-01](https://cloud.githubusercontent.com/assets/21071440/19099914/a73b0e64-8a88-11e6-9d61-5ab2fd72acfc.jpg)
![servernotreceivingping-02](https://cloud.githubusercontent.com/assets/21071440/19099915/a73da39a-8a88-11e6-9d3d-f0451aebc7f2.jpg)
![servernotreceivingping-03](https://cloud.githubusercontent.com/assets/21071440/19099916/a74004b4-8a88-11e6-89f2-76cef7d029f0.jpg)

**Comment by saurabhvyas** [comment]
I had the same problem , try navigation to public/js and modify the js file such that localhost is replaced by actual ip address

**Comment by jaredwolff** [comment]
@saurabhvyas which IP address are you using? If you're connecting to a VPS you need to make sure you have the correct ports open in the firewall (if enabled). If you're running this at home, you need to make sure you have the correct port forwarding set on your home router if you're trying to access from your public IP. 

I just recently went through the code again to ensure it works. I removed all unneeded dependencies like JQuery, etc. My best suggestion is run it on your computer first to make sure you understand the code and then move on to integrating it into your project.

**Comment by jaredwolff** [comment]
@NuzumPat this was a change to Socket.io. They had implemented an internal debugging mode which used the same "commands." I've updated the code to accomodate for this.

**Comment by saurabhvyas** [comment]
@jaredwolff I was earlier using localhost as my ip in js file , I updated this to actual ip like 192.168.1.220:5000 and it worked

**Comment by jaredwolff** [comment]
@saurabhvyas glad it work so now! Enjoy.
